name: Build linux

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [x64]
        mode: [debug]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1

    # Install dependencies
    - name: Update apt repositories
      run: sudo apt-get update
      
    - name: Install GCC12
      shell: bash
      run:  |
          sudo apt update
          sudo apt install gcc-12 g++-12
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 110 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
          
    # Install xmake
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: '2.6.5'

    # Update xmake repository (in order to have the file that will be cached)
    - name: Update xmake repository
      run: xmake repo --update

    # Setup compilation mode and install project dependencies
    - name: Configure xmake and install dependencies
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --yes

    # Build the game
    - name: Build
      run: xmake
    
    # Create install
    #- name: Install
    # run: xmake install -o packaged

    # Upload artifacts
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}
    #    path: packaged/bin/**
